name: Staging Deployment
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: FTP Deployment
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.ftp_server_staging }}
          username: ${{ secrets.ftp_user_staging }}
          password: ${{ secrets.ftp_password_staging }}
          protocol: ftps
